### PR TITLE
Support for sending a community when disabled in healthcheck.py

### PR DESCRIPTION
**Pull request by martbhell**
This change is [Reviewable](https://reviewable.io/reviews/exa-networks/exabgp/786)

### CODE REVIEW

**Comment by vincentbernat** [comment]
:+1:

**Comment by vincentbernat** [comment]
Hummm, after reading again, does ExaBGP accepts if you provide both `--community` and `--disabled-community`?

**Comment by martbhell** [comment]
Good point. I'll try after lunch.

**Comment by martbhell** [comment]
Yeah it broke stuff when one used both. Think I fixed it in #787 now.

**Pull request merged**
