### PR TITLE
Adding support for extended communities in healthcheck.py

### PR DESCRIPTION
**Pull request by bcollet**
This change is [Reviewable](https://reviewable.io/reviews/exa-networks/exabgp/545)

### CODE REVIEW

**Comment by thomas-mangin** [comment]
Thank you Benjamin, much appreciated.
@vincentbernat - Vincent happy to merge ?

**Comment by thomas-mangin** [comment]
ping @vincentbernat

**Comment by thomas-mangin** [comment]
last ping to @vincentbernat

**Comment by vincentbernat** [comment]
For some reason, I didn't receive the notifications for this thread. OK for me!

**Comment by thomas-mangin** [comment]
:-) Thanks

**Comment by bcollet** [comment]
Great! Thanks @vincentbernat, @thomas-mangin :-)

**Pull request merged**
