### PR TITLE
Debian packaging update

### PR DESCRIPTION
**Pull request by vincentbernat**
Hey!

Updates for Debian packaging.

The important change is the fourth one, about not relying on the content of /etc/default/exabgp to start the daemon. This is considered bad practice. Instead, I rely on the presence of /etc/exabgp/exabgp.conf to start the daemon (including for systemd). The package doesn't ship `/etc/default/exabgp` anymore (useless) and we don't ship `/etc/exabgp/exabgp.conf` either. Previously, an empty configuration file was shipped. The post/preinst scripts are taking care of the migration. A user that did not modify `/etc/exabgp/exabgp.conf` will see the file removed while a user who did modify the configuration will keep it.

### CODE REVIEW

**Comment by thomas-mangin** [comment]
@vincentbernat you should be able to push to the repository.
The dependencies presents in requirements.txt may be a good thing to add (as otherwise your code and the test suite will not run) respectively ipaddr and psutil
I think nose could be omitted.

**Comment by thomas-mangin** [comment]
And I forgot to be polite and say thank you - I blame multitasking for it :tongue:

**Comment by thomas-mangin** [comment]
I see that debian/exabgp.preinst does reference the latest version number, should this file be generated from setup.py when I tag a new release ? Or should the code be able to determine the version from the packaged files ?

**Comment by vincentbernat** [comment]
No, it should stay as is. This is the first version where an empty `/etc/exabgp/exabgp.conf` is not shipped.

**Comment by vincentbernat** [comment]
Nope, I cannot push directly to the repository. :)

**Comment by thomas-mangin** [comment]
Should work now or I need a GitHub course :smile:

**Comment by vincentbernat** [comment]
You're safe. It worked!

**Pull request merged**
