### PR TITLE
Minor fix to make docker build work

### PR DESCRIPTION
**Pull request by paddy01**
docker build failed due to error in Dockerfile.remote - fixed.

### CODE REVIEW

**Comment by thomas-mangin** [comment]
COPY was not supported by Podman last time I checked, hence the RUN echo syntax.

**Comment by thomas-mangin** [comment]
Thank you @paddy01 - if it fixes your problem, please feel free to close the issue/PR.

**Comment by paddy01** [comment]
Have to reopen this as it doesn't work in a raw docker build .. it does work under docker compose build tho which is odd. -- I'll remake it to use echo for both instead to make it compliant, sorry!

**Comment by paddy01** [comment]
This should do it.

**Pull request merged**
