### PR TITLE
[v3.4] allow sudo to setup ips and manage loopback dynamically

### PR DESCRIPTION
**Pull request by ahmet2mir**
# 2 features in this PR

To install and test it
```
pip install git+https://github.com/ahmet2mir/exabgp.git@sudo_dyn_ip_34
```
## 1 - Use sudo instead of drop privileges

When I take a look to apache2 or nginx configuration, both of them launch a daemon as root, then this deamon launch child with the specified service user.

httpd example

```
root     15174       1   /usr/sbin/httpd
apache   11502   15174   /usr/sbin/httpd
```

But running exabgp as root then remove privileges could be very dangerous (I remember some hacking in C bypassing the setuid, very old in my memory :)) So I add an option to prepend cmd ip with sudo.

Current `lo` conf

```
[root@myhost  ~]# ip a s dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
```

Start the daemon, run as exabgp

```
[root@myhost  ~]# systemctl start exabgp
[root@myhost  ~]# ps -ef | grep exabgp
exabgp   14259     1  0 10:15 ?        00:00:00 /bin/python -m exabgp healthcheck --withdraw-on-down --next-hop 10.1.0.1 --disable /etc/exabgp/maintenance/myhost.lan --cmd /bin/curl -sf http://localhost:8080 -o /dev/null --name myvip.lan --up-metric 100 --ip 10.2.0.1
```

Get the logs

```
[root@myhost  ~]# journalctl -fxu exabgp
Jan 31 10:16:39 rancher-slave02.sys.lab.ingenico.com healthcheck-myvip.lan[15089]: Uncaught exception: Command '[u'ip', u'address', u'add', '10.2.0.1/32', u'dev', u'lo']' returned non-zero exit status 2
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/exabgp/application/healthcheck.py", line 598, in main
  setup_ips(options.ips, options.label, options.sudo)
File "/usr/lib/python2.7/site-packages/exabgp/application/healthcheck.py", line 329, in setup_ips
  cmd, stdout=fnull, stderr=fnull)
File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
  raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '[u'ip', u'address', u'add', '10.2.0.1/32', u'dev', u'lo']' returned non-zero exit status 2
```

Now add sudo power + sudo flags but only on dev lo

```
[root@myhost  ~]# cat /etc/sudoers.d/20_exabgp
exabgp ALL=(ALL) NOPASSWD: /sbin/ip address add * dev lo,/sbin/ip address delete * dev lo
```

Test conf

```
[root@myhost  ~]# su - exabgp
[exabgp@myhost  ~]$ sudo ip address add 10.2.0.1/32 dev eth0
[sudo] password for exabgp: ^C
[exabgp@myhost  ~]$ sudo ip address add 10.2.0.1/32 dev lo
[exabgp@myhost  ~]$ ip a s dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.2.0.1/32 scope global lo
       valid_lft forever preferred_lft forever
[exabgp@myhost  ~]$ sudo ip address delete 10.2.0.1/32 dev lo
[exabgp@myhost  ~]$ ip a s dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
```

Now add --sudo to healthcheck

```
[root@myhost  ~]# ip a s dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
```

Start the daemon, run as exabgp with --sudo
```
[root@myhost  ~]# systemctl start exabgp
[root@myhost  ~]# ps -ef | grep exabgp
exabgp   14259     1  0 10:15 ?        00:00:00 /bin/python -m exabgp healthcheck --withdraw-on-down --next-hop 10.1.0.1 --disable /etc/exabgp/maintenance/myhost.lan --cmd /bin/curl -sf http://localhost:8080 -o /dev/null --name myvip.lan --up-metric 100 --ip 10.2.0.1 --sudo
```

Verify

```
[root@myhost  ~]# ip a s dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.2.0.1/32 scope global lo
       valid_lft forever preferred_lft forever
```

## 2 - Dynamic IP setup

In some cases, I have to remove the loopback when the service fail.
For example a 3 nodes DB cluster with a VIP announcing the master, other nodes have to report to the master on the VIP. If exabgp don't announce the route, the loopback is present, so the slave talk to himself. So we have to remove the loopback too. For now we use an hack with `--up-execute="sudo ifup lo:x"` or `--down-execute="sudo ifdown lo:x"`.

I added `--dynamic-ip-setup` option to ensure that the loopback is remove when the state become DOWN or DISABLED, then restore it if become UP.

Start the daemon, run as exabgp with --sudo --dynamic-ip-setup

```
[root@myhost  ~]# ps -ef | grep exabgp
exabgp   14259     1  0 10:15 ?        00:00:00 /bin/python -m exabgp healthcheck --withdraw-on-down --next-hop 10.1.0.1 --disable /etc/exabgp/maintenance/myhost.lan --cmd /bin/curl -sf http://localhost:8080 -o /dev/null --name myvip.lan --up-metric 100 --ip 10.2.0.1 --sudo --dynamic-ip-setup
```

```
[root@myhost  ~]# ip a s dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.2.0.1/32 scope global lo
       valid_lft forever preferred_lft forever
```

I stop my webserver and check logs

```
[root@myhost  ~]# journalctl -fxu exabgp
xxxxx: service down, deleting loopback ips
```

When the service is DOWN, lo don't have the IP

```
[root@myhost  ~]# ip a s dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
```

I start the webserver and logs say

```
[root@myhost  ~]# journalctl -fxu exabgp
xxxxx: service up, restoring loopback ips
```

Check ip

```
[root@myhost  ~]# ip a s dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.2.0.1/32 scope global lo
       valid_lft forever preferred_lft forever
```

Loopback is back :)

(We are using 3.4.17, I'm porting to the master branch in another PR)

---
This change is [Reviewable](https://reviewable.io/reviews/exa-networks/exabgp/571)

### CODE REVIEW

**Comment by vincentbernat** [comment]
It would have been better to do two PR, one for sudo and one for dynamic IP. But, great work on documenting the PR!

I have no objection for the sudo stuff.

I would have said that it's not the job of the script to do the dynamic IP configuration, but since it's already doing that at start, I am also OK with that.

So, if @thomas-mangin is OK, we can merge.

**Comment by ahmet2mir** [comment]
@vincentbernat probably, I prefer small PR, but the code is not huge, very few lines. If needed I can split it.

For the dynamic IP, I think that `up/down-execute` is more oriented for monitoring stuff, not OS. Is for these reason we decided to add this feature: separate low level in code / high level in some user scripts.

**Comment by thomas-mangin** [comment]
Can we please have this patch forward ported to master ? I believe if should be a matter of copy and paste and submitting a PR

**Comment by thomas-mangin** [comment]
GRRR - Thanks to an issue (fixing it) with the new experimental proxy I am running on my laptop -  this thank you was not posted ! so ... logged to Chrome and ....

Thank you @ahmet2mir for doing this work and submitting the PR ...

**Comment by ahmet2mir** [comment]
@thomas-mangin my pleasure, thanks for the team for the awesome work :)

**Pull request merged**
