### PR TITLE
Add @Attribute.register() for AS4Path

### PR DESCRIPTION
**Pull request by atwardowski**
Fix for issue #359

[Review on Reviewable](https://reviewable.io/reviews/exa-networks/exabgp/360)

### CODE REVIEW

**Comment by thomas-mangin** [comment]
Please explain the fix and add some credit in the CHANGELOG and I will merge.
Thank you very much for this fix.

**Comment by atwardowski** [comment]
Commit 61c4671 moved Attribute.register_attribute(AS4Path) out of `lib/exabgp/bgp/message/update/attribute/__init__.py` but missed adding the decorator to the class. in `lib/exabgp/bgp/message/update/attribute/aspath.py`.

**Comment by thomas-mangin** [comment]
sorry, when I meant explain the fix - I meant write a one liner in the CHANGELOG

**Comment by thomas-mangin** [comment]
Thank you very much :+1:

**Pull request merged**
