### PR TITLE
Test if capability message is received as expected

### PR DESCRIPTION
**Pull request by ton31337**

### CODE REVIEW

**Comment by thomas-mangin** [comment]
can I please ask you to reformat the function in another PR so I can see what changed please?

**Comment by thomas-mangin** [comment]
As the bgp program is changed bgp-3.6 will also be updated to match the changes otherwise I will have no chance to make Python 3.6 build stable - ATM they fail once in a while but I do not know why (and I need to build a old Ubuntu to debug) so I have left it for later.

**Comment by thomas-mangin** [comment]
Forget my comment about formatting ..

**Comment by ton31337** [comment]
I can drop that reformatting commit for sure, should I drop it or leave it as it is now?

**Comment by ton31337** [comment]
Will do in a minute ;)

**Comment by thomas-mangin** [comment]
ok, it does not allow to test for an OPEN and then an UPDATE - that's ok, it can be added later. It does not break anything.

**Comment by ton31337** [comment]
Gh, don't have 3.6 right now...

**Pull request merged**
