### PR TITLE
RT5 support changes for exaBGP

### PR DESCRIPTION
**Pull request by garci66**
Here are the changes I have written. I had not submitted them before because I believe there is some issue when the class tries to register the route parser. Right now, neither RT2 or RT5 can be registered it seems (but the EVPN adjacency forms fine).

I had no time to debug it but I believe its a good start. And looks like the code can still be merged quite straightforwardly!

### CODE REVIEW

**Comment by thomas-mangin** [comment]
@garci66 - Thanks a lot - Could I ask you if you could rebase on my tree, as the merge will otherwise fail. If it is too hard, I will try to get git to do my binding :smile:

**Comment by garci66** [comment]
Willing to help.. but just need a tip on how to do it. Is it just git rebase? I guess I need to add this repo (instead of my fork) as a master

**Comment by thomas-mangin** [comment]
... I was asking as I do not know myself ...
I tried to apply the patches to my branch but it failed as there is some conflicts due to some thing being renamed/moved. I can apply your changes "by hand" if it is not easy for you- I will just pretend to be you so credit is well kept :wink:

**Comment by garci66** [comment]
at least here it tells me the changes can be merged automatically (to your master here in exa). Is it not the master branch you're committing to? (sorry.. im a networking person, not really into git so im playing by ear here)...

**Pull request merged**
