### PR TITLE
update/traffic: fix IPv6 translation

### PR DESCRIPTION
**Pull request by rzalamena**
Fix the following configuration parsing error:

```
configuration | error message: illegal IP address string passed to inet_pton
```

### CODE REVIEW

**Comment by rzalamena** [comment]
This partially fixes #927 for ExaBGP 4.2.

**Comment by thomas-mangin** [comment]
Hi @rzalamena - this patch looks good, how did you test it please ?

**Comment by rzalamena** [comment]
@thomas-mangin using the configuration file from issue #1004 .

```
neighbor 10.0.1.1 {
router-id 10.0.1.101;
local-address 10.0.1.101;
local-as 100;
peer-as 100;
flow {
route {
match {
source 1.1.1.2/32;
destination 3.3.3.3/32;
packet-length <200;
}
then {
redirect 50.0.0.2;
rate-limit 55;
}
}
#end route 1
route {
match {
source 1::2/128/0;
destination 3::3/128/0;
packet-length <200;
}
then {
redirect 50::2;
rate-limit 55;
}
}
#end route 2
}
}
```

This line `redirect 50::2;` causes the parse failure.

Thanks for the quick responses!

**Comment by thomas-mangin** [comment]
@rzalamena could you forward port the patch to master too please?

**Pull request merged**
