### PR TITLE
Don't resolve configuration symlinks

### PR DESCRIPTION
**Pull request by juise**

### CODE REVIEW

**Comment by thomas-mangin** [comment]
Hello @juise - thank you for the PR but why should we not do this in your opinion ?

**Comment by juise** [comment]
I’m using symlinks for atomic configuration change, and to keep history. So, every changes in configuration written in the new file, and symlink to it atomically changed, after that I call “reload” command. But... config link is resolved into first symlinked file by exabgp... So, I think it will be better don’t resolve symlinks explicitly

**Comment by thomas-mangin** [comment]
I understand the use case. However, the test we are performing should be against the file and not the symlink, and we do not want to have a race condition with someone changing the symlink between the test and opening the file (as ExaBGP can run as root). It is not as bad as we do not write but still good practice.

**Comment by thomas-mangin** [comment]
@juise - thank you implemented differently with https://github.com/Exa-Networks/exabgp/commit/594000bc382afe359b63a1b69a97b597a38d262a but the result should be the same.

**Comment by juise** [comment]
Awesome, this fix very useful for me, thanks!

**Pull request closed without merging**
