### PR TITLE
Support additional sub-type of BGP-Prefix-SID for SRv6-VPN

### PR DESCRIPTION
**Pull request by slankdev**
This commit makes exabgp to support additional sub-type of prefix-sid
path attributes for SRv6 VPNv4. following ietf-drafts define about it.

prefix-sid type-4 is defined as generic srv6-vpn-sid, that is used by
Cisco IOS-XR's VPNv4 with SRv6 backend. prefix-sid type-5 is
defined as srv6-L3-vpn-sid that is used by Cisco NX-OS's VPNv4 with
SRv6 backend.

Also type-4 is already deprecated but this values is used some production
network fields (i.e. softbank mobile backend), so supporting type-4 is
really important.  In current IETF status, type-5 is preferred and IOS-XR
seems to support type-5 for VPNv4 with SRv6 backend.

- https://tools.ietf.org/html/draft-dawra-idr-srv6-vpn-04
- https://tools.ietf.org/html/draft-dawra-idr-srv6-vpn-05

Signed-off-by: Hiroki Shirokura <slank.dev@gmail.com>

### CODE REVIEW

**Comment by slankdev** [comment]
Above force push fix the commiter's and author's info.

**Comment by ruissalo** [comment]
Hi @slankdev could paste the logs that show successful parsing of the new attribute?

--
Evelio

**Comment by slankdev** [comment]
Hi Evelio. Thank you for reply. I found my mistake. (I didn't care the receive side of this feature) I'll check that.

currently, following log are generated and BGP-NOTIFICATION is sent and flap bgp connection state.
```
env exabgp.tcp.bind="0.0.0.0" exabgp.tcp.port=179 ./exabgp /exabgp.conf.R1
04:17:16 | 234    | welcome       | Thank you for using ExaBGP
04:17:16 | 234    | version       | prefix-sid-srv6-vpn-987bd841efa06e64bf7b44ceabdd133dd27b86a7
04:17:16 | 234    | interpreter   | 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
04:17:16 | 234    | os            | Linux R1 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64
04:17:16 | 234    | installation  | /root/exabgp
04:17:16 | 234    | advice        | environment file missing
04:17:16 | 234    | advice        | generate it using "exabgp --fi > /root/exabgp/etc/exabgp/exabgp.env"
04:17:16 | 234    | cli           | could not find the named pipes (exabgp.in and exabgp.out) required for the cli
04:17:16 | 234    | cli           | we scanned the following folders (the number is your PID):
04:17:16 | 234    | cli control   |  - /run/exabgp/
04:17:16 | 234    | cli control   |  - /run/0/
04:17:16 | 234    | cli control   |  - /run/
04:17:16 | 234    | cli control   |  - /var/run/exabgp/
04:17:16 | 234    | cli control   |  - /var/run/0/
04:17:16 | 234    | cli control   |  - /var/run/
04:17:16 | 234    | cli control   |  - /root/exabgp/run/exabgp/
04:17:16 | 234    | cli control   |  - /root/exabgp/run/0/
04:17:16 | 234    | cli control   |  - /root/exabgp/run/
04:17:16 | 234    | cli control   |  - /root/exabgp/var/run/exabgp/
04:17:16 | 234    | cli control   |  - /root/exabgp/var/run/0/
04:17:16 | 234    | cli control   |  - /root/exabgp/var/run/
04:17:16 | 234    | cli control   | please make them in one of the folder with the following commands:
04:17:16 | 234    | cli control   | > mkfifo /root/exabgp/sbin/run/exabgp.{in,out}
04:17:16 | 234    | cli control   | > chmod 600 /root/exabgp/sbin/run/exabgp.{in,out}
04:17:16 | 234    | configuration | performing reload of exabgp prefix-sid-srv6-vpn-987bd841efa06e64bf7b44ceabdd133dd27b86a7
04:17:16 | 234    | reactor       | loaded new configuration successfully
04:17:17 | 234    | reactor       | connected to peer-1 with incoming-1 10.0.0.2-10.0.0.1
04:17:18 | 234    | reactor       | connected to peer-1 with incoming-2 10.0.0.2-10.0.0.1
04:17:19 | 234    | reactor       | connected to peer-1 with incoming-3 10.0.0.2-10.0.0.1
04:17:21 | 234    | reactor       | connected to peer-1 with incoming-4 10.0.0.2-10.0.0.1
04:17:24 | 234    | reactor       | connected to peer-1 with incoming-5 10.0.0.2-10.0.0.1
04:17:28 | 234    | reactor       | connected to peer-1 with incoming-6 10.0.0.2-10.0.0.1
04:17:43 | 234    | reactor       | connected to peer-1 with incoming-7 10.0.0.2-10.0.0.1
04:17:43 | 234    | reactor       | connected to peer-1 with incoming-8 10.0.0.2-10.0.0.1
04:17:45 | 234    | reactor       | connected to peer-1 with incoming-9 10.0.0.2-10.0.0.1
04:17:47 | 234    | reactor       | connected to peer-1 with incoming-10 10.0.0.2-10.0.0.1
04:17:50 | 234    | reactor       | connected to peer-1 with incoming-11 10.0.0.2-10.0.0.1
04:17:55 | 234    | reactor       | connected to peer-1 with incoming-12 10.0.0.2-10.0.0.1
04:18:00 | 234    | reactor       | connected to peer-1 with incoming-13 10.0.0.2-10.0.0.1
...
```

**Comment by slankdev** [comment]
I force-pushed to fix some problems on receive-side. and to fix extended-nexthop-capa's issues.

@ruissalo . following is the logs that show successful parsing of the new attribute.
```
07:43:20 | 79     | welcome       | Thank you for using ExaBGP
07:43:20 | 79     | version       | 4.1.2-d006a34a
07:43:20 | 79     | interpreter   | 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
07:43:20 | 79     | os            | Linux R1 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64
07:43:20 | 79     | installation  | /root/exabgp
07:43:20 | 79     | advice        | environment file missing
07:43:20 | 79     | advice        | generate it using "exabgp --fi > /root/exabgp/etc/exabgp/exabgp.env"
07:43:20 | 79     | cli           | could not find the named pipes (exabgp.in and exabgp.out) required for the cli
07:43:20 | 79     | cli           | we scanned the following folders (the number is your PID):
07:43:20 | 79     | cli control   |  - /run/exabgp/
07:43:20 | 79     | cli control   |  - /run/0/
07:43:20 | 79     | cli control   |  - /run/
07:43:20 | 79     | cli control   |  - /var/run/exabgp/
07:43:20 | 79     | cli control   |  - /var/run/0/
07:43:20 | 79     | cli control   |  - /var/run/
07:43:20 | 79     | cli control   |  - /root/exabgp/run/exabgp/
07:43:20 | 79     | cli control   |  - /root/exabgp/run/0/
07:43:20 | 79     | cli control   |  - /root/exabgp/run/
07:43:20 | 79     | cli control   |  - /root/exabgp/var/run/exabgp/
07:43:20 | 79     | cli control   |  - /root/exabgp/var/run/0/
07:43:20 | 79     | cli control   |  - /root/exabgp/var/run/
07:43:20 | 79     | cli control   | please make them in one of the folder with the following commands:
07:43:20 | 79     | cli control   | > mkfifo //run/exabgp.{in,out}
07:43:20 | 79     | cli control   | > chmod 600 //run/exabgp.{in,out}
07:43:20 | 79     | network       | listening for BGP session(s) on 10.0.0.1:179
07:43:20 | 79     | configuration | performing reload of exabgp 4.1.2-d006a34a
07:43:20 | 79     | configuration | > process          | 'announce-routes'
07:43:20 | 79     | configuration | . run              | '/output.py'
07:43:20 | 79     | configuration | . encoder          | 'json'
07:43:20 | 79     | configuration | < process          |
07:43:20 | 79     | configuration | > neighbor         | '10.0.0.2'
07:43:20 | 79     | configuration | . router-id        | '1.1.1.1'
07:43:20 | 79     | configuration | . local-address    | '10.0.0.1'
07:43:20 | 79     | configuration | . local-as         | '1'
07:43:20 | 79     | configuration | . peer-as          | '2'
07:43:20 | 79     | configuration | > capability       |
07:43:20 | 79     | configuration | . nexthop          | 'true'
07:43:20 | 79     | configuration | < capability       |
07:43:20 | 79     | configuration | > family           |
07:43:20 | 79     | configuration | . ipv4             | 'unicast'
07:43:21 | 79     | configuration | . ipv4             | 'mpls-vpn'
07:43:21 | 79     | configuration | . ipv6             | 'unicast'
07:43:21 | 79     | configuration | . ipv6             | 'mpls-vpn'
07:43:21 | 79     | configuration | < family           |
07:43:21 | 79     | configuration | > nexthop          |
07:43:21 | 79     | configuration | . ipv4             | 'mpls-vpn' 'ipv6'
07:43:21 | 79     | configuration | < nexthop          |
07:43:21 | 79     | configuration | > static           |
07:43:21 | 79     | configuration | < static           |
07:43:21 | 79     | configuration | > api              |
07:43:21 | 79     | configuration | . processes        | '[' 'announce-routes' ']'
07:43:21 | 79     | configuration | > receive          |
07:43:21 | 79     | configuration | . parsed           |
07:43:21 | 79     | configuration | . update           |
07:43:21 | 79     | configuration | < receive          |
07:43:21 | 79     | configuration | < api              |
07:43:21 | 79     | configuration | < neighbor         |
07:43:21 | 79     | reactor       | new peer: neighbor 10.0.0.2 local-ip 10.0.0.1 local-as 1 peer-as 2 router-id 1.1.1.1 family-allowed in-open
07:43:21 | 79     | network       | listening for BGP session(s) on 10.0.0.1:179
07:43:21 | 79     | reactor       | loaded new configuration successfully
07:43:21 | 79     | process       | forked process announce-routes
07:43:21 | 79     | reactor       | initialising connection to peer-1
07:43:21 | 79     | reactor       | initialising connection to peer-1
07:43:22 | 79     | reactor       | initialising connection to peer-1
07:43:24 | 79     | reactor       | initialising connection to peer-1
07:43:26 | 79     | reactor       | async | 62412858-35d8-11ea-ab4c-c6cd7b498fff | checking for new connection(s)
07:43:26 | 79     | network       | connection from 10.0.0.1
07:43:26 | 79     | network       | new connection received incoming-1 10.0.0.2-10.0.0.1
07:43:26 | 79     | peer-1        | state machine for the peer is IDLE
07:43:26 | 79     | network       | accepted connection from incoming-1 10.0.0.2-10.0.0.1
07:43:26 | 79     | reactor       | initialising connection to peer-1
07:43:26 | 79     | reactor       | connected to peer-1 with incoming-1 10.0.0.2-10.0.0.1
07:43:26 | 79     | peer-1        | >> EOR(s)
07:43:26 | 79     | routes        | withdrawn NLRI none
07:43:26 | 79     | routes        | announced NLRI none
07:43:26 | 79     | peer-1        | << UPDATE #1
07:43:26 | 79     | peer-1        |    UPDATE #1 nlri  (  15) 10.0.0.0/24 label 3 next-hop cafe::1 rd 1:1
07:43:26 | 79     | routes        | withdrawn NLRI none
07:43:26 | 79     | routes        | announced NLRI none
07:43:26 | 79     | peer-1        | << UPDATE #2
07:43:26 | 79     | peer-1        |    UPDATE #2 nlri  (  15) 10.1.0.0/24 label 3 next-hop cafe::1 rd 1:2
07:43:26 | 79     | peer-1        | << UPDATE #3
07:43:26 | 79     | peer-1        |    UPDATE #3 nlri  (   4) eor 1/1 (ipv4 unicast)
07:43:26 | 79     | peer-1        | << UPDATE #4
07:43:26 | 79     | peer-1        |    UPDATE #4 nlri  (  11) eor 1/128 (ipv4 mpls-vpn)
07:43:26 | 79     | peer-1        | << UPDATE #5
07:43:26 | 79     | peer-1        |    UPDATE #5 nlri  (  11) eor 2/1 (ipv6 unicast)
07:43:26 | 79     | peer-1        | << UPDATE #6
07:43:26 | 79     | peer-1        |    UPDATE #6 nlri  (  11) eor 2/128 (ipv6 mpls-vpn)
```

and following log is json outputs by exabgp, when exabgp received routes with prefix-sid-type-4(vpnsid), and prefix-sid-type-5(l3vpnsid).
```
{
  "exabgp": "4.0.1",
  "time": 1578901406.5917861,
  "host": "R1",
  "pid": 79,
  "ppid": 0,
  "counter": 1,
  "type": "update",
  "neighbor": {
    "address": {
      "local": "10.0.0.1",
      "peer": "10.0.0.2"
    },
    "asn": {
      "local": 1,
      "peer": 2
    },
    "direction": "receive",
    "message": {
      "update": {
        "attribute": {
          "origin": "igp",
          "as-path": [
            2
          ],
          "confederation-path": [],
          "extended-community": [
            {
              "value": 842122827661313,
              "string": "target:65000:1"
            }
          ],
          "bgp-prefix-sid": {
            "srv6-vpn-sid": "2001:1::10"
          }
        },
        "announce": {
          "ipv4 mpls-vpn": {
            "cafe::1": [
              {
                "nlri": "10.0.0.0/24",
                "label": [
                  [
                    3
                  ]
                ],
                "rd": "1:1"
              }
            ]
          }
        }
      }
    }
  }
}
{
  "exabgp": "4.0.1",
  "time": 1578901406.5935879,
  "host": "R1",
  "pid": 79,
  "ppid": 0,
  "counter": 2,
  "type": "update",
  "neighbor": {
    "address": {
      "local": "10.0.0.1",
      "peer": "10.0.0.2"
    },
    "asn": {
      "local": 1,
      "peer": 2
    },
    "direction": "receive",
    "message": {
      "update": {
        "attribute": {
          "origin": "igp",
          "as-path": [
            2
          ],
          "confederation-path": [],
          "extended-community": [
            {
              "value": 842122827661314,
              "string": "target:65000:2"
            }
          ],
          "bgp-prefix-sid": {
            "srv6-l3vpn-sid": "2001:1::20"
          }
        },
        "announce": {
          "ipv4 mpls-vpn": {
            "cafe::1": [
              {
                "nlri": "10.1.0.0/24",
                "label": [
                  [
                    3
                  ]
                ],
                "rd": "1:2"
              }
            ]
          }
        }
      }
    }
  }
}
...(snip)...
```

finally, following is the configuration.
```
process announce-routes {
        run /output.py;
        encoder json;
}

neighbor 10.0.0.2 {
        router-id 1.1.1.1;
        local-address 10.0.0.1;
        local-as 1;
        peer-as 2;

        capability {
                nexthop true;
        }

        family {
                ipv4 unicast;
                ipv4 mpls-vpn;
                ipv6 unicast;
                ipv6 mpls-vpn;
        }

        nexthop {
                ipv4 mpls-vpn ipv6;
        }

        static {
        }

        api {
                processes [ announce-routes ];
                receive {
                        parsed;
                        update;
                }
        }
}
```

**Comment by thomas-mangin** [comment]
Thank you very much for this feature @slankdev - we will need to add some unit and functional testing for the feature but I will merge the patch as it looks good.

**Comment by thomas-mangin** [comment]
@slankdev could you please re-run the same with "exabgp -d" so we can add a test for the packet decoding ?.Alternatively, we could also use any packet dump of an update. Thank you very much.

**Pull request merged**
