### PR TITLE
Add Support for Prefix-SID type-5 and type-6 

### PR DESCRIPTION
**Pull request by proelbtn**
This patch includes:

- remove deprecated Prefix-SID definition (type-2 and type-4)
- implement Prefix-SID type-5 and type-6
- add new configuration for Prefix-SID type-5 and type-6

reference: https://datatracker.ietf.org/doc/draft-ietf-bess-srv6-services/11/

### CODE REVIEW

**Comment by thomas-mangin** [comment]
Thank you for this work, much appreciated.

In order to be able to merge this work, a JSON representation of the objects need to be added to the classes: all the JSON functions were left as `TODO`.

**Comment by proelbtn** [comment]
Yes, I'm considering JSON format for them and I was so tired last night that I fell asleep.

**Comment by proelbtn** [comment]
@thomas-mangin I added JSON representation and fixed some small things. It's ok to be reviewed it.

**Comment by thomas-mangin** [comment]
Thank you I will review. There was no rush - I hope you are rested now 🥱

**Comment by thomas-mangin** [comment]
Ok, it seems that it is breaking backwards compatibility with the previous type names (VPN and l3vpn) so it should be included in `doc/CHANGELOG.rst` and the RFC supported on `https://github.com/Exa-Networks/exabgp/wiki/RFC-Information` also but otherwise LGTM.

If you want to add the CHANGELOG entry to the patch set, I will then merge 👍

**Comment by proelbtn** [comment]
@thomas-mangin updated CHANGELOG

**Pull request merged**
