### PR TITLE
Make disabled-community work with community

### PR DESCRIPTION
**Pull request by martbhell**
Fix bug introduced in #786 which when one had both disabled-community and community in the healthcheck config then it added community [] twice to the announce line. Which crashed exabgp shortly after these errors:

<pre>
exabgp: out loop, skipping, not time yet
</pre>

---
This change is [Reviewable](https://reviewable.io/reviews/exa-networks/exabgp/787)

### CODE REVIEW

**Comment by martbhell** [comment]
Hmm.. I was a bit too early :/ 

Scenarios tested:

 - both disabled-community and community
   - normally: community appended
   - down and disabled: community changed to disabled-community
 - only community
   - normally, down and disabled: community appended
 - only disabled-community
  - no community on normal
  - no community added on down and disabled

**Comment by vincentbernat** [comment]
Maybe, shorter code:

```python
if options.community or options.disabled_community:
    community = options.community
    if target in (states.DOWN, states.DISABLED) and options.disabled_community:
        community = options.disabled_community
    announce = "{0} community [ {1} ]".format(announce, community)
```

**Comment by martbhell** [comment]
Nice! Added another commit that I tested also.

That shorter code almost worked, just needed another conditional to test that community was not None before adding it to the announce string.

**Comment by vincentbernat** [comment]
Thanks! In master, there is support for extended and large communities, we'll see if someone wants an extended or large disabled community.

**Pull request merged**
