### PR TITLE
* Created redhat/python-exabgp.spec.git

### PR DESCRIPTION
**Pull request by leleobhz**
Closes https://github.com/Exa-Networks/exabgp/issues/626

---
This change is [Reviewable](https://reviewable.io/reviews/exa-networks/exabgp/627)

### CODE REVIEW

**Comment by thomas-mangin** [comment]
I will merge. See my related question in 626 please.

**Comment by lukehinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[redhat/python-exabgp.spec.git, line 5 at r1](https://reviewable.io:443/reviews/exa-networks/exabgp/627#-KjrXfoAgMaIOJXwCu1e:-KjrXfoAgMaIOJXwCu1f:bbmac37) ([raw file](https://github.com/exa-networks/exabgp/blob/25219ea45a854951f652c0297535c455811403a1/redhat/python-exabgp.spec.git#L5)):*
> 3.4.11

Could this be set to master please? 3.4.11 is an older release now. 

---

*[redhat/python-exabgp.spec.git, line 17 at r1](https://reviewable.io:443/reviews/exa-networks/exabgp/627#-KjrXG0b_CWY78rJIjRZ:-KjrXG0coazK4dsAPIYc:b-1u9ll0) ([raw file](https://github.com/exa-networks/exabgp/blob/25219ea45a854951f652c0297535c455811403a1/redhat/python-exabgp.spec.git#L17)):*
> ```
> 
> BuildRequires:  python-setuptools
> Requires:       python2 >= 2.6, python-ipaddr
> ```

Could you set python-ipaddr on a new line, for example:

Requires:       python2 >= 2.6
Requires:       python-ipaddr

This format is needed for CentOS and Fedora build systems, where it won't work with csv / array sequences

---

*[redhat/python-exabgp.spec.git, line 87 at r1](https://reviewable.io:443/reviews/exa-networks/exabgp/627#-KjrXpVjeGLJwD26aiYW:-KjrXpVjeGLJwD26aiYX:b-n2gifm) ([raw file](https://github.com/exa-networks/exabgp/blob/25219ea45a854951f652c0297535c455811403a1/redhat/python-exabgp.spec.git#L87)):*
> ```
> %{_mandir}/man5/*
> 
> %changelog
> ```

We should update the %changelog with the fixes / additions made. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/exa-networks/exabgp/627)*

**Comment by thomas-mangin** [comment]
@lukehinds I will merge and you can provide a patch to provide the change ..
perhaps we need two specs files: one for 3.4 and one for 4.0.0 (which will be released in a matters of days)

**Comment by leleobhz** [comment]
@thomas-mangin Ive commited the fix for these changes.

I want to remember this spec is to build .rpm from git versions, just to allow easy and clean deploy of git versions.

Should I send a new PR?

**Pull request merged**
