### PR TITLE
Fix healthcheck.py to use /var/run/log for syslog on NetBSD

### PR DESCRIPTION
**Pull request by he32**
This allows it to work on NetBSD too.

---
This change is [Reviewable](https://reviewable.io/reviews/exa-networks/exabgp/672)

### CODE REVIEW

**Comment by he32** [comment]
Insisting on a list of OSes here probably isn't the best strategy, but I know
too little python to make a constructive suggestion for an improvement.

**Comment by thomas-mangin** [comment]
Thank you

**Comment by thomas-mangin** [comment]
It merged in a branch it seems - porting to 3.4 and master

**Comment by vincentbernat** [comment]
Yes, that's unfortunate but Python doesn't abstract that. By default, it uses UDP on 514, but on many systems, the syslog daemon doesn't listen on the UDP port. A loop to test all possibilities, regardless of the OS, could also be used (check if file exists and is a socket).

**Pull request merged**
