### PR TITLE
Fix for healthcheck.py for non-Linux systems

### PR DESCRIPTION
**Pull request by he32**
Two fixes for the non-Linux ifconfig route:
 * Also match "inet alias <address> netmask <netmask>", i.e. optionally match "alias ".
 * Don't insist on leading spaces, those are removed by strip() already...

### CODE REVIEW

**Comment by vincentbernat** [comment]
LGTM.

**Comment by thomas-mangin** [comment]
@he32 Thank you for this patch.

**Comment by thomas-mangin** [comment]
@he32 hi, as I do not have your name could you please update the CHANGELOG to add attribution of your work :+1:

**Comment by he32** [comment]
You're welcome.  I created pull request #228 for that.

**Pull request merged**
