### PR TITLE
Fix some issues reported by lintian

### PR DESCRIPTION
**Pull request by debian-janitor**
Fix some issues reported by lintian
* Trim trailing whitespace. ([file-contains-trailing-whitespace](https://lintian.debian.org/tags/file-contains-trailing-whitespace.html))
* Use secure copyright file specification URI. ([insecure-copyright-format-uri](https://lintian.debian.org/tags/insecure-copyright-format-uri.html))
* Bump debhelper from old 9 to 12. ([package-uses-old-debhelper-compat-version](https://lintian.debian.org/tags/package-uses-old-debhelper-compat-version.html))
* Set debhelper-compat version in Build-Depends. ([uses-debhelper-compat-file](https://lintian.debian.org/tags/uses-debhelper-compat-file.html))
* Set upstream metadata fields: Repository, Repository-Browse. ([upstream-metadata-file-is-missing](https://lintian.debian.org/tags/upstream-metadata-file-is-missing.html))
* Fix day-of-week for changelog entries 3.0.11-1, 2.0.6-1, 2.0.5-1, 2.0.2-1, 2.0.1-1, 2.0.0-1, 1.3.4-2, 1.3.4-1, 1.3.3-2, 1.3.3-1, 1.3.1-2, 1.3.1-1, 1.3.0-1, 1.2.0-2. ([debian-changelog-has-wrong-day-of-week](https://lintian.debian.org/tags/debian-changelog-has-wrong-day-of-week.html))

This merge proposal was created automatically by the
[Janitor bot](https://janitor.debian.net/lintian-fixes).

You can follow up to this merge proposal as you normally would.

Build and test logs for this branch can be found at
https://janitor.debian.net/lintian-fixes/pkg/exabgp/b820d87f-5758-4123-b974-9c3c32303435.

### CODE REVIEW

**Comment by thomas-mangin** [comment]
@vincentbernat I assume one should just merge :-)

**Comment by thomas-mangin** [comment]
@vincentbernat I assume you are just very busy .. hopefully you will be able to give this a look soon :-)

**Comment by thomas-mangin** [comment]
@vincentbernat I merged as it seems pretty uncontroversial.

**Comment by vincentbernat** [comment]
Sorry, I didn't spot your emails despite multiple attempts!

It's funny: I didn't know about this project!

The change will make the life of people wanting to build ExaBGP packages for anything else than Debian Stretch more difficult. I propose to rollback the change about too old debhelper version. The corresponding [Lintian tag](https://lintian.debian.org/tags/package-uses-old-debhelper-compat-version.html) is classified as pedantic (which means nobody should really pay attention).

**Comment by thomas-mangin** [comment]
Ack and done.

**Comment by thomas-mangin** [comment]
Did I misunderstand - were you only looking to rollback part of the changes ?

**Comment by vincentbernat** [comment]
Yes, only a small part. I'll do it myself!

**Comment by thomas-mangin** [comment]
@vincentbernat thank you - sorry for being a bit thick here!

**Comment by vincentbernat** [comment]
I have pushed a partial revert with an inverted commit message. Just in case this was not confusing enough! :)

I'll package 4.2.1 when you release it!

**Comment by thomas-mangin** [comment]
@vincentbernat should we port the change you have on your branch to master so the diff is as little as possible. And I released 4.2.1 hopefully fixing all the bugs with 4.2.0.

**Comment by vincentbernat** [comment]
❦ 14 janvier 2020 10:55 -08, Thomas Mangin <notifications@github.com>:

> @vincentbernat should we port the change you have on your branch to
> master so the diff is as little as possible. And I released 4.2.1
> hopefully fixing all the bugs with 4.2.0.

There is no debian/ directory in master. What do you mean?

**Comment by debian-janitor** [comment]
On Tue, Jan 14, 2020 at 12:04:54AM -0800, Vincent Bernat wrote:
> The change will make the life of people wanting to build ExaBGP packages for anything else than Debian Stretch more difficult. I propose to rollback the change about too old debhelper version. The corresponding [Lintian tag](https://lintian.debian.org/tags/package-uses-old-debhelper-compat-version.html) is classified as pedantic (which means nobody should really pay attention).

I've updated the janitor configuration to not propose any changes for
exabgp that don't work in oldstable. Let me know if I should change
that to e.g.  oldoldstable.

You can also set this in the package itself:

$ echo 'compat-release = oldoldstable' > debian/lintian-brush.conf

Jelmer

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by thomas-mangin** [comment]
@vincentbernat bringing the Debian folder into master to allow people to build package from master if they wish.

**Comment by vincentbernat** [comment]
@thomas-mangin We specifically removed the `debian/` directory from master. It's easier for me this way (for official packages), but I remember having better arguments about this. Instead, there is instructions on how to import the debian directory from `debian/sid` branch.

@debian-janitor I think oldstable is quite enough as it should cover the two latest versions of Ubuntu. I'll push a commit to set it in the package, as you suggest.

**Pull request merged**
