### PR TITLE
Support for link bandwidth extended community

### PR DESCRIPTION
**Pull request by pereiro**
Hi!
I've added support for bandwidth community (just few lines of code)
Hope it will be useful)

Tested with Juniper MX series

https://www.juniper.net/techpubs/en_US/junos16.1/topics/usage-guidelines/policy-defining-bgp-communities-and-extended-communities-for-use-in-routing-policy-match-conditions.html

---
This change is [Reviewable](https://reviewable.io/reviews/exa-networks/exabgp/538)

### CODE REVIEW

**Comment by thomas-mangin** [comment]
This is great news, thank you. Are you able to backport this patch to 3.4 ?

**Comment by thomas-mangin** [comment]
Also, it seems that you added the announcement but not decoding of the message.. would it be too much to ask if you could add the decoding too please ?

**Comment by thomas-mangin** [comment]
@Pereiro can you update the patch or will you not be able to ?

**Comment by ruissalo** [comment]
Hi Thomas, 

Sure I can do that if needed.

**Comment by thomas-mangin** [comment]
Hi - I can not merge due to a conflict but implementing it fully. https://tools.ietf.org/html/draft-ietf-idr-link-bandwidth-06 says 0x40, 0x04 and not 0x00, 0x04 - am I missing something ?

**Comment by thomas-mangin** [comment]
implemented with 36e8fcd8 - some testing would be appreciated.

**Comment by omkartikare** [comment]
Hey Thomas, is there a syntax sample on how we can use link bw ? Is it like "....extended-community [bandwidth: 100000]"

**Comment by mnanduri** [comment]
I am running into an issue against Junos devices. Below is the config and capture from Juniper device. I see it as "unknown iana 4004". Any ideas.

exabgp config:

neighbor 192.168.1.155 {
    local-as 65;
    peer-as 65535;
    local-address 192.168.1.142;
    router-id 1.1.1.1;
    family {
        ipv4 nlri-mpls;
    }
    capability {
        add-path send;
    }

announce {
    ipv4 {
      nlri-mpls 192.168.2.250  next-hop 5.5.5.2 label [ 801000 800001 800002 ] path-information 1.1.1.1 extended-community [ bandwidth:1:10000000 ];
      nlri-mpls 192.168.2.250  next-hop 5.5.5.1 label [ 801001 800001 800002 ] path-information 1.1.1.2 extended-community [ bandwidth:1:20000000 ];
      }
   }
}

Junos is getting the community based on traceoptions as "4004:65535:1259902592"

Oct 13 20:47:23.568334
Oct 13 20:47:23.568334 BGP RECV 192.168.1.142+36181 -> 192.168.1.155+179
Oct 13 20:47:23.568368 BGP RECV message type 2 (Update) length 81
Oct 13 20:47:23.568377 BGP RECV Update PDU length 81
Oct 13 20:47:23.568387 BGP RECV flags 0x40 code Origin(1): IGP
Oct 13 20:47:23.568397 BGP RECV flags 0x40 code ASPath(2) length 0: <null>
Oct 13 20:47:23.568408 BGP RECV flags 0x40 code NextHop(3): 5.5.5.2
Oct 13 20:47:23.568416 BGP RECV flags 0x40 code LocalPref(5): 100

**### Oct 13 20:47:23.568425 BGP RECV flags 0xc0 code Extended Communities(16): 4004:65535:1259902592**

Oct 13 20:47:23.568434 BGP RECV flags 0x80 code MP_reach(14): AFI/SAFI 1/4
Oct 13 20:47:23.568451 BGP RECV 	nhop 5.5.5.2 len 4
Oct 13 20:47:23.568485 BGP RECV 	192.168.2.250/32 (label 801000) (label 800001) (label 800002)
Oct 13 20:47:23.568560 bgp_rcv_nlri: Peer 192.168.1.142 (Internal AS 65535)
Oct 13 20:47:23.568580 bgp_rcv_nlri: 192.168.2.250/32

Show route shows is as - "Communities: unknown iana 4004"

lab@vmx17.4-r2# run show route 192.168.2.250 extensive

inet.0: 44 destinations, 56 routes (44 active, 0 holddown, 0 hidden)
192.168.2.250/32 (2 entries, 1 announced)
TSI:
KRT in-kernel 192.168.2.250/32 -> {indirect(1048579)}
Page 0 idx 0, (group iBGP type Internal) Type 1 val 0xb20c148 (adv_entry)
   Advertised metrics:
     Flags: Nexthop Change
     Nexthop: Self
     Localpref: 1000
     AS path: [65535] 65 I
     Communities: color:0:0 unknown iana 4004
Path 192.168.2.250 from 192.168.1.142 Vector len 4.  Val: 0
        *BGP    Preference: 170/-1001
                Next hop type: Indirect, Next hop index: 0
                Address: 0xb3a6a30
                Next-hop reference count: 3
                Source: 192.168.1.142
                Next hop type: Router, Next hop index: 608
                Next hop: 5.5.5.2 via ge-0/0/2.0, selected
                Label operation: Push 800002, Push 800001, Push 801001(top)
                Label TTL action: prop-ttl, prop-ttl, prop-ttl(top)
                Load balance label: Label 800002: None; Label 800001: None; Label 801001: None;
                Label element ptr: 0xb3a6780
                Label parent element ptr: 0x0
                Label element references: 3
                Label element child references: 0
                Label element lsp id: 0
                Session Id: 0x140
                Protocol next hop: 5.5.5.1
                Label operation: Push 800002, Push 800001, Push 801001(top)
                Label TTL action: prop-ttl, prop-ttl, prop-ttl(top)
                Load balance label: Label 800002: None; Label 800001: None; Label 801001: None;
                Indirect next hop: 0xc9b5900 1048579 INH Session ID: 0x18a
                State: <Active Ext>
                Local AS: 65535 Peer AS:    65
                Age: 25 	Metric2: 30
                Validation State: unverified
                ORR Generation-ID: 0
                Task: BGP_65.192.168.1.142
                Announcement bits (3): 0-KRT 3-BGP_RT_Background 4-Resolve tree 4
                AS path: 65 I
                **### Communities: unknown iana 4004**
                Accepted

**Comment by thomas-mangin** [comment]
The feature is not merged - I need to look into it (and forgot).

**Comment by thomas-mangin** [comment]
@omkartikare I just added the feature as the patch had issues (such as0x0004 and not 0x4004 and the patch was incomplete ). So AFAICS the feature is in and I can close this PR. Thank you for the PR.

**Pull request closed without merging**
