### PR TITLE
Implement software version capability for BGP

### PR DESCRIPTION
**Pull request by ton31337**
https://datatracker.ietf.org/doc/html/draft-abraitis-bgp-version-capability

This is already implemented by FRR, GoBGP, freertr, Wireshark, some more.

E.g.:

```
$ vtysh -c 'show bgp neighbor 127.0.0.1 json' | jq '."127.0.0.1".neighborCapabilities.softwareVersion'
{
  "advertisedSoftwareVersion": "FRRouting/10.2-dev-MyOwnFRRVersion-g8ca262943f",
  "receivedSoftwareVersion": "ExaBGP/5.0.0"
}
```

### CODE REVIEW

**Comment by ton31337** [comment]
I'll rework this to be per-capability knob.

**Comment by ton31337** [comment]
Great ;) Any suggestions on what should I use for a "shorter" _version_ of VERSION?

**Comment by thomas-mangin** [comment]
Using the version.py file is right; modifying its content for the main branch is what is required as it is already modified on release, with the exact release version.

It could be main-COMMIT-YYMMDD, which could have COMMIT as unknown when the commit is unknown and YYMMDD as the build date if the commit is unset. Otherwise, it could be the date of the exabgp.

**Comment by thomas-mangin** [comment]
The version is taken out of the changelog:
https://github.com/Exa-Networks/exabgp/blob/main/release#L199

Therefore the github release has it.
https://github.com/Exa-Networks/exabgp/blob/main/release#L57

Probably need to update the PyPI release to the same version
https://github.com/Exa-Networks/exabgp/blob/main/release#L281

**Comment by ton31337** [comment]
So, maybe it's just fine using `version` overall? It will use EXABGP_VERSION (numeric) for released packages, while branch + sha for git-based installations.

**Comment by thomas-mangin** [comment]
The release code needs to update how PYPI is released to match GitHub. I will deal with it. As the code could be run within a folder where the .git folder has been removed, it needs to provide a consistent output, hence my suggestion of tag and date.

**Comment by ton31337** [comment]
I changed some bits, is this what we were talking about?

**Comment by thomas-mangin** [comment]
I can later look in the exabgp version string issue, but before I can merge, I will need a test for the OPEN.

**Comment by ton31337** [comment]
Sure, will do this.

**Comment by ton31337** [comment]
Seems that the version to test is non-deterministic. Will think on how to overcome this for CI/QA.

**Comment by thomas-mangin** [comment]
I am fixing other things so please wait for my patch:
```
    def json(self):
        return '{ "software-version": "%s" }' % self.software_version
```
is what you need to fix as {} in a fstring does not work well.

**Comment by thomas-mangin** [comment]
Do you want to implement https://www.rfc-editor.org/rfc/rfc9072.html ?

**Comment by ton31337** [comment]
> Do you want to implement https://www.rfc-editor.org/rfc/rfc9072.html ?

Sure, will check later, now traveling a bit.

**Comment by thomas-mangin** [comment]
The work on the software version is now completed. Thank you.

**Pull request merged**
