### PR TITLE
Add python3 to the pypi classifier

### PR DESCRIPTION
**Pull request by tmmorin**
This change is [Reviewable](https://reviewable.io/reviews/exa-networks/exabgp/644)

### CODE REVIEW

**Comment by thomas-mangin** [comment]
LOL - I noticed the same thing myself during the week-end and already patched this (I set this to 3.6).
Thank you for your help !

**Comment by tmmorin** [comment]
Ok, thanks!

**Comment by tmmorin** [comment]
One thing though: I think you should keep 2.7, not replace it !

**Comment by thomas-mangin** [comment]
ok - thanks ..

**Pull request closed without merging**
