### PR TITLE
Add ExaZK as use case

### PR DESCRIPTION
**Pull request by ton31337**
Add ExaZK as use case.
/cc @thomas-mangin

[Review on Reviewable](https://reviewable.io/reviews/exa-networks/exabgp/364)

### CODE REVIEW

**Comment by thomas-mangin** [comment]
Hi Donatas, happy to add your solution to the list ( i believe it is already on the wiki )
As both yours an Blablacar have both the same name, it would be nice to be able to present the difference between both in the summary text.

**Comment by ton31337** [comment]
@thomas-mangin is it better? Actually this is in development stage, but we are using it already, so many updates will be pushed soon in 1-2 months.

**Comment by thomas-mangin** [comment]
I was more wondering how a reader could decided what was best for them between the two solution ? Are they working the same way ?

**Comment by ton31337** [comment]
@thomas-mangin as I understand the principle is the same as with previous one, except that this is written in ruby language and more lightweight (it's just one file solution).

**Comment by thomas-mangin** [comment]
what about changing the text like this ?
  * [ExaZK](https://github.com/shtouff/exazk) a python solution to interface ExaBGP & ZooKeeper to achieve service HA
 + * [exazk](https://github.com/ton31337/exazk) a ruby solution to interface ExaBGP & ZooKeeper to achieve service HA

**Comment by ton31337** [comment]
@thomas-mangin :+1:

**Comment by thomas-mangin** [comment]
Great . Do you want to update your commit request ? Or I can do it - as you with.

**Comment by thomas-mangin** [comment]
Sorry - done.

**Pull request merged**
