### PR TITLE
Display correct uname for --version flag

### PR DESCRIPTION
**Pull request by earies**
change platform.version() call to platform.uname() to display correct uname string

[Review on Reviewable](https://reviewable.io/reviews/exa-networks/exabgp/327)

### CODE REVIEW

**Comment by thomas-mangin** [comment]
Thank you for for your contribution .. however, I am not sure what it does :
```
>>> import platform
>>> platform.version()
'Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64'
>>> ' '.join(platform.uname()[:5])
'Darwin Thomas-MacBook.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64'
```

I fail to see what you think the current output is missing. ...

**Comment by earies** [comment]
The platform module only returns the 3rd element for version()

```
def version():

    """ Returns the system's release version, e.g. '#3 on degas'

        An empty string is returned if the value cannot be determined.

    """
    return uname()[3]
```
With OSX - this is the 3rd element of "uname -a" which makes more sense than in Linux (as you've shown)

```
Python 2.7.5 (default, May 29 2013, 02:28:51) 
[GCC 4.8.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> platform.version()
'#32 SMP Mon Aug 17 11:12:04 MDT 2015'
>>> platform.uname()[3]
'#32 SMP Mon Aug 17 11:12:04 MDT 2015'
>>> platform.uname()[:5]
('Linux', 'bitz', '4.1.6-20150817', '#32 SMP Mon Aug 17 11:12:04 MDT 2015', 'x86_64')

```

Current:

```
[exa@bitz ~]$ exabgp --version
ExaBGP : 3.9.0
Python : 2.7.5 (default, May 29 2013, 02:28:51)  [GCC 4.8.0]
Uname  : #32 SMP Mon Aug 17 11:12:04 MDT 2015
```

After

```
[exa@bitz ~]$ exabgp --version
ExaBGP : 3.9.0
Python : 2.7.5 (default, May 29 2013, 02:28:51)  [GCC 4.8.0]
Uname  : Linux bitz 4.1.6-20150817 #32 SMP Mon Aug 17 11:12:04 MDT 2015 x86_64
```

**Comment by thomas-mangin** [comment]
Thank you the for the explanation

**Comment by thomas-mangin** [comment]
Thank you for noticing the issue. Merged.

**Pull request merged**
